[tox]
envlist = py312-test, lint, mypy, docs
requires = tox-uv>=1

[testenv:lint]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    pylint --rcfile=pylintrc openedx_webhooks tests
    isort --check-only openedx_webhooks tests

[testenv:mypy]
runner = uv-venv-lock-runner
dependency_groups = quality
commands = mypy openedx_webhooks tests

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
commands = pytest --cov=openedx_webhooks --cov=tests --cov-report=xml {posargs}

[testenv:docs]
runner = uv-venv-lock-runner
basepython = python3.12
changedir = {toxinidir}/docs
dependency_groups = doc
allowlist_externals = make
commands =
    make html
